services:
  - type: worker
    name: chainlink-staking-alert
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python alert.py
    envVars:
      - key: INFURA_URL
        value: https://mainnet.infura.io/v3/YOUR_INFURA_KEY
      - key: TELEGRAM_BOT_TOKEN
        value: YOUR_TELEGRAM_BOT_TOKEN
      - key: TELEGRAM_CHAT_ID
        value: YOUR_CHAT_ID
